# Generated by Django 5.0.3 on 2026-05-10 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_add_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_designe_461a08_idx',
            old_name='projects_designer_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='projectitem',
            new_name='project_ite_project_e2cfc8_idx',
            old_name='project_items_project_pinned_idx',
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='designer',
            field=models.ForeignKey(limit_choices_to={'role': 'INTERIOR_DESIGNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
