# Generated by Django 5.0.3 on 2026-05-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0002_initial'),
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='reference_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspired_commissions', to='artisans.product'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='commissions.commission'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['designer', 'status'], name='commissions_designe_9bb0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['artisan', 'status'], name='commissions_artisan_19b7de_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'created_at'], name='commissions_status_eec601_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['commission', 'status'], name='milestones_commiss_003b77_idx'),
        ),
    ]
