# Generated by Django 5.0.3 on 2026-05-09 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('specialisation', models.CharField(choices=[('RESIDENTIAL', 'Residential Design'), ('COMMERCIAL', 'Commercial Design'), ('HOSPITALITY', 'Hospitality Design'), ('RETAIL', 'Retail Design'), ('HEALTHCARE', 'Healthcare Design'), ('MIXED', 'Mixed/General')], max_length=20)),
                ('bio', models.TextField(max_length=1000)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('portfolio_images', models.JSONField(default=list)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'designer_profiles',
                'indexes': [models.Index(fields=['specialisation'], name='designer_pr_special_93f99f_idx')],
            },
        ),
    ]
