# Generated by Django 5.0.3 on 2026-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_update_role_to_interior_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('NAIROBI', 'Nairobi'), ('MOMBASA', 'Mombasa'), ('KISUMU', 'Kisumu'), ('NAKURU', 'Nakuru'), ('KIAMBU', 'Kiambu'), ('KISII', 'Kisii'), ('LAMU', 'Lamu'), ('KAJIADO', 'Kajiado'), ('MACHAKOS', 'Machakos'), ('KILIFI', 'Kilifi')], max_length=50),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='designerprofile',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='designerprofile',
            name='specialisation',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential Design'), ('COMMERCIAL', 'Commercial Design'), ('HOSPITALITY', 'Hospitality Design'), ('RETAIL', 'Retail Design'), ('HEALTHCARE', 'Healthcare Design'), ('MIXED', 'Mixed/General')], default='MIXED', max_length=20),
        ),
    ]
