# Generated by Django 5.0.3 on 2026-05-02 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000)),
                ('county', models.CharField(choices=[('NAIROBI', 'Nairobi'), ('MOMBASA', 'Mombasa'), ('KISUMU', 'Kisumu'), ('NAKURU', 'Nakuru'), ('KIAMBU', 'Kiambu'), ('KISII', 'Kisii'), ('LAMU', 'Lamu'), ('KAJIADO', 'Kajiado'), ('MACHAKOS', 'Machakos'), ('KILIFI', 'Kilifi'), ('KWALE', 'Kwale'), ('TAITA_TAVETA', 'Taita Taveta'), ('GARISSA', 'Garissa'), ('WAJIR', 'Wajir'), ('MANDERA', 'Mandera'), ('MARSABIT', 'Marsabit'), ('ISIOLO', 'Isiolo'), ('MERU', 'Meru'), ('THARAKA_NITHI', 'Tharaka Nithi'), ('EMBU', 'Embu'), ('KITUI', 'Kitui'), ('MAKUENI', 'Makueni'), ('NYANDARUA', 'Nyandarua'), ('NYERI', 'Nyeri'), ('KIRINYAGA', 'Kirinyaga'), ('MURANGA', "Murang'a"), ('TURKANA', 'Turkana'), ('WEST_POKOT', 'West Pokot'), ('SAMBURU', 'Samburu'), ('TRANS_NZOIA', 'Trans Nzoia'), ('UASIN_GISHU', 'Uasin Gishu'), ('ELGEYO_MARAKWET', 'Elgeyo Marakwet'), ('NANDI', 'Nandi'), ('BARINGO', 'Baringo'), ('LAIKIPIA', 'Laikipia'), ('NAROK', 'Narok'), ('KERICHO', 'Kericho'), ('BOMET', 'Bomet'), ('KAKAMEGA', 'Kakamega'), ('VIHIGA', 'Vihiga'), ('BUNGOMA', 'Bungoma'), ('BUSIA', 'Busia'), ('SIAYA', 'Siaya'), ('HOMA_BAY', 'Homa Bay'), ('MIGORI', 'Migori'), ('NYAMIRA', 'Nyamira')], max_length=50)),
                ('town', models.CharField(max_length=100)),
                ('craft_specialty', models.CharField(choices=[('SOAPSTONE', 'Kisii Soapstone Carving'), ('FURNITURE', 'Lamu Furniture'), ('BEADWORK', 'Maasai Beadwork'), ('BASKETS', 'Woven Baskets'), ('POTTERY', 'Pottery & Ceramics'), ('TEXTILES', 'Traditional Textiles'), ('WOODCARVING', 'Wood Carving'), ('METALWORK', 'Metal Crafts'), ('JEWELRY', 'Handmade Jewelry'), ('LEATHER', 'Leather Crafts'), ('PAINTING', 'Traditional Painting')], max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('workshop_address', models.TextField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_registration', models.CharField(blank=True, max_length=100)),
                ('portfolio_images', models.JSONField(default=list)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_commissions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artisan_profiles',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('material', models.CharField(max_length=100)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('COMMISSIONABLE', 'Available for Commission'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], default='COMMISSIONABLE', max_length=20)),
                ('primary_image', models.URLField()),
                ('additional_images', models.JSONField(default=list)),
                ('craft_category', models.CharField(max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('commission_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
