# Generated by Django 5.0.3 on 2026-05-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='artisans.artisanprofile'),
        ),
        migrations.AddIndex(
            model_name='artisanprofile',
            index=models.Index(fields=['county', 'craft_specialty'], name='artisan_pro_county_cbf1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='artisanprofile',
            index=models.Index(fields=['average_rating'], name='artisan_pro_average_f8e777_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'craft_category'], name='products_status_17ba29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['material'], name='products_materia_a1405d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_kes'], name='products_price_k_8abcf6_idx'),
        ),
    ]
